# Config file used to generate inputs for Beeline using Synthetic networks
global_settings:
  model_dir: "data"
  output_dir: "Synthetic"
  do_simulations: True
  do_post_processing: True
  modeltype: 'hill'

jobs:
  - name: "dyn-LI"
    model_definition: "dyn-linear.txt"
    model_initial_conditions: "dyn-linear_ics.txt"
    simulation_time: 5
    num_cells: 1000
    do_parallel: True

  - name: "dyn-LL"
    model_definition: "dyn-linear-long.txt"
    model_initial_conditions: "dyn-linear-long_ics.txt"
    simulation_time: 15
    num_cells: 1000
    do_parallel: True
    
  - name: "dyn-CY"
    model_definition: "dyn-cycle.txt"
    model_initial_conditions: "dyn-cycle_ics.txt"
    simulation_time: 8
    num_cells: 1000
    do_parallel: True    

  - name: "dyn-BF"
    model_definition: "dyn-bifurcating.txt"
    model_initial_conditions: "dyn-bifurcating_ics.txt"
    simulation_time: 8
    num_cells: 1000
    do_parallel: True
    nClusters: 2    

  - name: "dyn-BFC"
    model_definition: "dyn-bifurcating-converging.txt"
    model_initial_conditions: "dyn-bifurcating-converging_ics.txt"
    simulation_time: 8
    num_cells: 1000
    do_parallel: True
    nClusters: 2    

  - name: "dyn-TF"
    model_definition: "dyn-trifurcating.txt"
    model_initial_conditions: "dyn-trifurcating_ics.txt"
    simulation_time: 8
    num_cells: 1000
    do_parallel: True
    nClusters: 3
        
        
post_processing:
  GenSamples:
    - sample_size: 500
      nDatasets: 10

  DimRed:
    - perplexity: 100
