global_settings:
  model_dir: "data"
  output_dir: "outputs/misc"
  do_simulations: True
  do_post_processing: False
#  modeltype: 'heaviside'
  modeltype: 'hill'

jobs:
   - name: "dyn-LI-1"
     model_definition: "dyn-linear.txt"
#     model_initial_conditions: "dyn-linear_ics.txt"
     simulation_time: 10
     num_cells: 5000
     do_parallel: False
     sample_pars: True
     sample_std: 0.5
     identical_pars: True
##     nClusters: 3

#   - name: "EMT"
#     model_definition: "EMT.txt"
##     model_initial_conditions: "dyn-linear_ics.txt"
#     parameter_inputs_path: "EMT-inputs.txt"
#     simulation_time: 5
#     num_cells: 100
#     do_parallel: True
#     sample_pars: True
#     sample_std: 0.5
#     identical_pars: True
##     nClusters: 3


post_processing:
  Dropouts:
    - dropout: False
      nCells: 1000
      
  #   - dropout: False
  #     nCells: 100
  #     drop_cutoff: 0.5
  #     drop_prob: 0.5
      
  #   - dropout: False
  #     nCells: 100
  #     drop_cutoff: 0.7
  #     drop_prob: 0.7
      
  # Slingshot:
  #   - perplexity: 400
