global_settings:
  model_dir: "data"
  output_dir: "Synthetic-H"
  do_simulations: True
  do_post_processing: False
  modeltype: 'heaviside'
#  modeltype: 'hill'

jobs:
  - name: "dyn-LL-1"
    model_definition: "dyn-linear-long.txt"
    model_initial_conditions: "dyn-linear-long_ics.txt"
    simulation_time: 9
    num_cells: 400
    do_parallel: True
    sample_cells: False
  # - name: "dyn-LI-1"
  #   model_definition: "dyn-linear.txt"
  #   model_initial_conditions: "dyn-linear_ics.txt"
  #   simulation_time: 7
  #   num_cells: 200
  #   do_parallel: True
  #   sample_cells: False

  # - name: "dyn-BF-1"
  #   model_definition: "dyn-bifurcating.txt"
  #   model_initial_conditions: "dyn-bifurcating_ics.txt"
  #   simulation_time: 5
  #   num_cells: 500
  #   do_parallel: True
  #   sample_cells: False
  #   nClusters: 2

  # - name: "dyn-TF-1"
  #   model_definition: "dyn-trifurcating.txt"
  #   model_initial_conditions: "dyn-trifurcating_ics.txt"
  #   simulation_time: 8
  #   num_cells: 500
  #   do_parallel: True
  #   sample_cells: False
  #   nClusters: 3

  # - name: "dyn-CY-1"
  #   model_definition: "dyn-cycle.txt"
  #   model_initial_conditions: "dyn-cycle_ics.txt"
  #   simulation_time: 8
  #   num_cells: 500
  #   do_parallel: True
  #   sample_cells: False
  #   nClusters: 1

post_processing:
  Dropouts:
    - dropout: False
      nCells: 1000
      
  #   - dropout: False
  #     nCells: 100
  #     drop_cutoff: 0.5
  #     drop_prob: 0.5
      
  #   - dropout: False
  #     nCells: 100
  #     drop_cutoff: 0.7
  #     drop_prob: 0.7
      
  # Slingshot:
  #   - perplexity: 400
