global_settings:
  model_dir: "data"
  output_dir: "outputs/curatednetworks"
  do_simulations: True
  do_post_processing: False
#  modeltype: 'heaviside'
  modeltype: 'hill'

jobs:
#  - name: "GSD"
#    model_definition: "GSD.txt"
#    model_initial_conditions: "GSD_ics.txt"
##    parameter_inputs_path: "dyn-consecutive-bifurcating-inputs.txt"
#    simulation_time: 8
#    num_cells: 3000
#    do_parallel: False
#    sample_pars: True
#    sample_std: 0.1
#    identical_pars: True
#    nClusters: 2

  - name: "EMT"
    model_definition: "EMT.txt"
    parameter_inputs_path: "EMT-inputs.txt"
    simulation_time: 10
    num_cells: 5000
    do_parallel: False
    sample_pars: True
    sample_std: 0.1
    identical_pars: True
    nClusters: 1

post_processing:
  Dropouts:
    - dropout: False
      nCells: 1000
      
  #   - dropout: False
  #     nCells: 100
  #     drop_cutoff: 0.5
  #     drop_prob: 0.5
      
  #   - dropout: False
  #     nCells: 100
  #     drop_cutoff: 0.7
  #     drop_prob: 0.7
      
  # Slingshot:
  #   - perplexity: 400
